### ISSUE TITLE
Znak "#" nie działa do wyłączenia.

### ISSUE THREAD

**Issue by Aides123** [zrdzn/LovelyDrop#24]
Hej, korzystam z pluginu od kilku godzin i jestem na etapie ustawiania.
Config wiadomości:
https://pastebin.com/fyz6yb7x

Te 3 na dole wiadomości próbowałem wyłączyć jednak w ich miejsce pojawia się
![image](https://user-images.githubusercontent.com/23367220/173637914-e32eef3f-886f-4a19-a04f-eda11954e86c.png)

Dodatkowo mam dwie propozycje:
- Opcja do ustawienia domyślnego dropu (EKWIPUNEK CZY NIE)
- Opcja do wyłączenia dropu cobblestone dla gracza

**Comment by Aides123** [comment]
Co do ostatniej propozycji "Opcja do wyłączenia dropu cobblestone dla gracza".
Dodałem do dropu COBBLESTONE bo zauważyłem że nie dropi w ogóle. To przy takim ustawieniu jest możliwość wyłączenia jego dropu jednak psuje to wtedy zaklęcie SILKTOUCH. 
Ustawiłem tak:
![image](https://user-images.githubusercontent.com/23367220/173641273-e53e3e6e-6b88-4d41-acc8-82f7f20a7c50.png)

**Comment by Aides123** [comment]
I jeszcze jedna rzecz. Usunąłem LORE z tego itemu i przy użyciu komendy do reload faktycznie usuwa lore jednak po restarcie lore wraca taki jaki jest default
![image](https://user-images.githubusercontent.com/23367220/173643076-58b4be82-9f59-4b4a-bbaa-2121b7190b15.png)

**Comment by zrdzn** [comment]
> Hej, korzystam z pluginu od kilku godzin i jestem na etapie ustawiania. Config wiadomości: https://pastebin.com/fyz6yb7x
> 
> Te 3 na dole wiadomości próbowałem wyłączyć jednak w ich miejsce pojawia się ![image](https://user-images.githubusercontent.com/23367220/173637914-e32eef3f-886f-4a19-a04f-eda11954e86c.png)
> 
> Dodatkowo mam dwie propozycje:
> 
> * Opcja do ustawienia domyślnego dropu (EKWIPUNEK CZY NIE)
> * Opcja do wyłączenia dropu cobblestone dla gracza

Messages disable resolved in #25
